17:44:04,948 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:44:04,949 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:44:32,946 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message User is missing required fields: username,emailAddress,userId
17:45:39,170 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:45:39,170 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:47:34,800 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:47:34,801 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:49:22,68 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message User is missing required fields: username,emailAddress,userId
17:49:33,562 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:49:33,563 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:50:35,404 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:50:35,410 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:51:47,605 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message User is missing required fields: username,emailAddress,userId
17:51:58,834 Error catcher ERROR Unknown except raised 1 validation error for Entry
output
  field required (type=value_error.missing)
17:51:58,846 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message CTRUKeygenResult is missing required fields: keys,entry
17:56:30,44 grpc._server ERROR Exception iterating responses: SympifyError: [Poly(4*x**31 + 2*x**29 - 2*x**28 - 2*x**27 + 2*x**26 - 2*x**23 - 2*x**22 + 4*x**21 + 4*x**20 - 2*x**15 + 2*x**14 - 4*x**13 - 2*x**12 + 2*x**11 + 2*x**9 - 2*x**8 + 4*x**7 - 2*x**6 - 2*x**5 + 2*x**4 + 2*x**3 + 3, x, domain='ZZ'), Poly(x**254 + x**253 + x**252 + x**250 + x**249 + x**248 + x**246 + x**245 + x**238 + x**236 + x**234 + x**233 + x**231 + x**230 + x**227 + x**225 + x**224 + x**222 + x**221 + x**220 + x**218 + x**215 + x**214 + x**213 + x**212 + x**210 + x**209 + x**205 + x**202 + x**201 + x**200 + x**199 + x**198 + x**193 + x**192 + x**188 + x**187 + x**184 + x**182 + x**179 + x**177 + x**171 + x**166 + x**164 + x**162 + x**159 + x**158 + x**157 + x**156 + x**149 + x**147 + x**144 + x**143 + x**142 + x**141 + x**139 + x**137 + x**136 + x**130 + x**127 + x**126 + x**122 + x**121 + x**120 + x**119 + x**118 + x**117 + x**114 + x**113 + x**111 + x**110 + x**108 + x**106 + x**104 + x**103 + x**102 + x**100 + x**99 + x**98 + x**91 + x**88 + x**84 + x**83 + x**82 + x**81 + x**78 + x**77 + x**75 + x**74 + x**73 + x**71 + x**69 + x**68 + x**65 + x**64 + x**63 + x**60 + x**57 + x**56 + x**55 + x**52 + x**50 + x**49 + x**47 + x**45 + x**44 + x**42 + x**41 + x**40 + x**38 + x**37 + x**34 + x**32 + x**31 + x**28 + x**27 + x**26 + x**24 + x**23 + x**22 + x**21 + x**19 + x**18 + x**17 + x**15 + x**13 + x**12 + x**9 + x**7 + x**5 + x**2 + x + 1, x, domain='ZZ')]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 118, in runDecaps
    alg.Decapsulate(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\timer.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 140, in Decapsulate
    mp = self._PKE_decrypt(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 93, in _PKE_decrypt
    m0 = ext_mod((self.sk * c) % self.R, self.q2)
  File "C:\Python39\lib\site-packages\sympy\polys\polytools.py", line 70, in wrapper
    g = _sympify(g)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 529, in _sympify
    return sympify(a, strict=True)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 450, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: [Poly(4*x**31 + 2*x**29 - 2*x**28 - 2*x**27 + 2*x**26 - 2*x**23 - 2*x**22 + 4*x**21 + 4*x**20 - 2*x**15 + 2*x**14 - 4*x**13 - 2*x**12 + 2*x**11 + 2*x**9 - 2*x**8 + 4*x**7 - 2*x**6 - 2*x**5 + 2*x**4 + 2*x**3 + 3, x, domain='ZZ'), Poly(x**254 + x**253 + x**252 + x**250 + x**249 + x**248 + x**246 + x**245 + x**238 + x**236 + x**234 + x**233 + x**231 + x**230 + x**227 + x**225 + x**224 + x**222 + x**221 + x**220 + x**218 + x**215 + x**214 + x**213 + x**212 + x**210 + x**209 + x**205 + x**202 + x**201 + x**200 + x**199 + x**198 + x**193 + x**192 + x**188 + x**187 + x**184 + x**182 + x**179 + x**177 + x**171 + x**166 + x**164 + x**162 + x**159 + x**158 + x**157 + x**156 + x**149 + x**147 + x**144 + x**143 + x**142 + x**141 + x**139 + x**137 + x**136 + x**130 + x**127 + x**126 + x**122 + x**121 + x**120 + x**119 + x**118 + x**117 + x**114 + x**113 + x**111 + x**110 + x**108 + x**106 + x**104 + x**103 + x**102 + x**100 + x**99 + x**98 + x**91 + x**88 + x**84 + x**83 + x**82 + x**81 + x**78 + x**77 + x**75 + x**74 + x**73 + x**71 + x**69 + x**68 + x**65 + x**64 + x**63 + x**60 + x**57 + x**56 + x**55 + x**52 + x**50 + x**49 + x**47 + x**45 + x**44 + x**42 + x**41 + x**40 + x**38 + x**37 + x**34 + x**32 + x**31 + x**28 + x**27 + x**26 + x**24 + x**23 + x**22 + x**21 + x**19 + x**18 + x**17 + x**15 + x**13 + x**12 + x**9 + x**7 + x**5 + x**2 + x + 1, x, domain='ZZ')]
17:59:33,531 grpc._server ERROR Exception iterating responses: SympifyError: [Poly(-2*x**31 - 4*x**30 + 2*x**29 + 2*x**28 + 4*x**27 - 4*x**26 - 2*x**24 + 2*x**23 - 2*x**22 - 2*x**20 - 2*x**19 + 2*x**18 - 2*x**16 - 2*x**14 - 2*x**13 + 2*x**12 + 2*x**11 - 2*x**8 + 2*x**7 + 2*x**6 - 2*x**5 + 2*x**3 - 4*x - 1, x, domain='ZZ'), Poly(x**255 + x**254 + x**252 + x**250 + x**249 + x**248 + x**244 + x**242 + x**241 + x**240 + x**234 + x**232 + x**231 + x**230 + x**229 + x**227 + x**224 + x**222 + x**221 + x**220 + x**219 + x**215 + x**214 + x**213 + x**211 + x**208 + x**206 + x**205 + x**203 + x**200 + x**199 + x**198 + x**194 + x**193 + x**188 + x**186 + x**185 + x**182 + x**180 + x**177 + x**174 + x**173 + x**172 + x**170 + x**169 + x**163 + x**160 + x**159 + x**158 + x**156 + x**155 + x**154 + x**152 + x**151 + x**145 + x**144 + x**142 + x**141 + x**135 + x**132 + x**131 + x**124 + x**122 + x**121 + x**119 + x**117 + x**115 + x**113 + x**111 + x**110 + x**109 + x**108 + x**106 + x**105 + x**104 + x**102 + x**101 + x**99 + x**97 + x**94 + x**93 + x**92 + x**88 + x**85 + x**84 + x**79 + x**75 + x**74 + x**71 + x**70 + x**67 + x**65 + x**64 + x**63 + x**61 + x**60 + x**59 + x**56 + x**49 + x**47 + x**42 + x**41 + x**40 + x**39 + x**35 + x**34 + x**32 + x**30 + x**28 + x**27 + x**26 + x**24 + x**20 + x**18 + x**15 + x**14 + x**12 + x**10 + x**7 + x**5 + x**4 + x**2, x, domain='ZZ')]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 119, in runDecaps
    alg.Decapsulate(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\timer.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 140, in Decapsulate
    mp = self._PKE_decrypt(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 93, in _PKE_decrypt
    m0 = ext_mod((self.sk * c) % self.R, self.q2)
  File "C:\Python39\lib\site-packages\sympy\polys\polytools.py", line 70, in wrapper
    g = _sympify(g)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 529, in _sympify
    return sympify(a, strict=True)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 450, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: [Poly(-2*x**31 - 4*x**30 + 2*x**29 + 2*x**28 + 4*x**27 - 4*x**26 - 2*x**24 + 2*x**23 - 2*x**22 - 2*x**20 - 2*x**19 + 2*x**18 - 2*x**16 - 2*x**14 - 2*x**13 + 2*x**12 + 2*x**11 - 2*x**8 + 2*x**7 + 2*x**6 - 2*x**5 + 2*x**3 - 4*x - 1, x, domain='ZZ'), Poly(x**255 + x**254 + x**252 + x**250 + x**249 + x**248 + x**244 + x**242 + x**241 + x**240 + x**234 + x**232 + x**231 + x**230 + x**229 + x**227 + x**224 + x**222 + x**221 + x**220 + x**219 + x**215 + x**214 + x**213 + x**211 + x**208 + x**206 + x**205 + x**203 + x**200 + x**199 + x**198 + x**194 + x**193 + x**188 + x**186 + x**185 + x**182 + x**180 + x**177 + x**174 + x**173 + x**172 + x**170 + x**169 + x**163 + x**160 + x**159 + x**158 + x**156 + x**155 + x**154 + x**152 + x**151 + x**145 + x**144 + x**142 + x**141 + x**135 + x**132 + x**131 + x**124 + x**122 + x**121 + x**119 + x**117 + x**115 + x**113 + x**111 + x**110 + x**109 + x**108 + x**106 + x**105 + x**104 + x**102 + x**101 + x**99 + x**97 + x**94 + x**93 + x**92 + x**88 + x**85 + x**84 + x**79 + x**75 + x**74 + x**71 + x**70 + x**67 + x**65 + x**64 + x**63 + x**61 + x**60 + x**59 + x**56 + x**49 + x**47 + x**42 + x**41 + x**40 + x**39 + x**35 + x**34 + x**32 + x**30 + x**28 + x**27 + x**26 + x**24 + x**20 + x**18 + x**15 + x**14 + x**12 + x**10 + x**7 + x**5 + x**4 + x**2, x, domain='ZZ')]
18:01:20,538 grpc._server ERROR Exception iterating responses: 'Poly' object has no attribute 'set_field'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 115, in runDecaps
    c = Poly(DerSequence().decode(b64decode(request.data)), x).set_field()
AttributeError: 'Poly' object has no attribute 'set_field'
18:02:14,58 grpc._server ERROR Exception iterating responses: SympifyError: [Poly(2*x**31 - 2*x**30 - 2*x**28 + 4*x**27 - 2*x**25 + 2*x**24 + 2*x**23 - 2*x**20 + 2*x**19 + 2*x**18 + 2*x**16 + 2*x**15 + 2*x**14 - 2*x**13 - 2*x**9 + 2*x**8 + 4*x**7 + 2*x**6 + 2*x**5 + 4*x**4 - 2*x**3 - 2*x - 1, x, domain='ZZ'), Poly(x**255 + x**254 + x**252 + x**251 + x**250 + x**248 + x**245 + x**243 + x**242 + x**238 + x**237 + x**232 + x**230 + x**228 + x**226 + x**225 + x**224 + x**217 + x**215 + x**209 + x**208 + x**207 + x**206 + x**204 + x**203 + x**201 + x**200 + x**198 + x**197 + x**196 + x**190 + x**185 + x**183 + x**179 + x**178 + x**177 + x**176 + x**175 + x**174 + x**172 + x**170 + x**169 + x**166 + x**165 + x**164 + x**162 + x**160 + x**157 + x**156 + x**155 + x**152 + x**151 + x**150 + x**148 + x**143 + x**142 + x**140 + x**139 + x**138 + x**137 + x**136 + x**133 + x**132 + x**131 + x**128 + x**127 + x**126 + x**125 + x**124 + x**123 + x**122 + x**120 + x**119 + x**118 + x**117 + x**116 + x**115 + x**114 + x**113 + x**112 + x**110 + x**109 + x**107 + x**101 + x**100 + x**99 + x**98 + x**88 + x**86 + x**85 + x**83 + x**82 + x**80 + x**77 + x**76 + x**73 + x**72 + x**69 + x**68 + x**62 + x**61 + x**59 + x**58 + x**57 + x**56 + x**55 + x**54 + x**53 + x**49 + x**48 + x**45 + x**40 + x**39 + x**38 + x**37 + x**36 + x**35 + x**33 + x**30 + x**29 + x**27 + x**26 + x**21 + x**20 + x**19 + x**18 + x**15 + x**10 + x**9 + x**6 + x**5 + x**4 + x**3 + 1, x, domain='ZZ')]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 121, in runDecaps
    alg.Decapsulate(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\timer.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 140, in Decapsulate
    mp = self._PKE_decrypt(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 93, in _PKE_decrypt
    m0 = ext_mod((self.sk * c) % self.R, self.q2)
  File "C:\Python39\lib\site-packages\sympy\polys\polytools.py", line 70, in wrapper
    g = _sympify(g)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 529, in _sympify
    return sympify(a, strict=True)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 450, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: [Poly(2*x**31 - 2*x**30 - 2*x**28 + 4*x**27 - 2*x**25 + 2*x**24 + 2*x**23 - 2*x**20 + 2*x**19 + 2*x**18 + 2*x**16 + 2*x**15 + 2*x**14 - 2*x**13 - 2*x**9 + 2*x**8 + 4*x**7 + 2*x**6 + 2*x**5 + 4*x**4 - 2*x**3 - 2*x - 1, x, domain='ZZ'), Poly(x**255 + x**254 + x**252 + x**251 + x**250 + x**248 + x**245 + x**243 + x**242 + x**238 + x**237 + x**232 + x**230 + x**228 + x**226 + x**225 + x**224 + x**217 + x**215 + x**209 + x**208 + x**207 + x**206 + x**204 + x**203 + x**201 + x**200 + x**198 + x**197 + x**196 + x**190 + x**185 + x**183 + x**179 + x**178 + x**177 + x**176 + x**175 + x**174 + x**172 + x**170 + x**169 + x**166 + x**165 + x**164 + x**162 + x**160 + x**157 + x**156 + x**155 + x**152 + x**151 + x**150 + x**148 + x**143 + x**142 + x**140 + x**139 + x**138 + x**137 + x**136 + x**133 + x**132 + x**131 + x**128 + x**127 + x**126 + x**125 + x**124 + x**123 + x**122 + x**120 + x**119 + x**118 + x**117 + x**116 + x**115 + x**114 + x**113 + x**112 + x**110 + x**109 + x**107 + x**101 + x**100 + x**99 + x**98 + x**88 + x**86 + x**85 + x**83 + x**82 + x**80 + x**77 + x**76 + x**73 + x**72 + x**69 + x**68 + x**62 + x**61 + x**59 + x**58 + x**57 + x**56 + x**55 + x**54 + x**53 + x**49 + x**48 + x**45 + x**40 + x**39 + x**38 + x**37 + x**36 + x**35 + x**33 + x**30 + x**29 + x**27 + x**26 + x**21 + x**20 + x**19 + x**18 + x**15 + x**10 + x**9 + x**6 + x**5 + x**4 + x**3 + 1, x, domain='ZZ')]
18:04:55,818 grpc._server ERROR Exception iterating responses: SympifyError: [Poly(-2*x**31 + 2*x**30 - 2*x**28 - 2*x**25 + 2*x**24 + 2*x**23 - 4*x**20 - 2*x**19 - 2*x**16 - 2*x**14 + 2*x**13 + 4*x**12 - 2*x**11 + 2*x**9 - 2*x**6 + 2*x**5 + 2*x**4 - 2*x**3 - 2*x**2 - 2*x + 3, x, domain='ZZ'), Poly(x**255 + x**254 + x**253 + x**251 + x**245 + x**244 + x**243 + x**238 + x**236 + x**235 + x**231 + x**229 + x**228 + x**227 + x**225 + x**223 + x**220 + x**219 + x**215 + x**214 + x**208 + x**207 + x**206 + x**203 + x**195 + x**188 + x**185 + x**184 + x**182 + x**181 + x**177 + x**176 + x**170 + x**168 + x**167 + x**165 + x**164 + x**163 + x**162 + x**157 + x**154 + x**153 + x**148 + x**145 + x**143 + x**141 + x**139 + x**138 + x**137 + x**136 + x**135 + x**132 + x**127 + x**126 + x**125 + x**120 + x**116 + x**115 + x**114 + x**111 + x**110 + x**109 + x**108 + x**106 + x**105 + x**103 + x**102 + x**100 + x**98 + x**95 + x**94 + x**93 + x**92 + x**91 + x**88 + x**86 + x**84 + x**81 + x**80 + x**79 + x**77 + x**76 + x**74 + x**70 + x**61 + x**60 + x**59 + x**58 + x**56 + x**55 + x**54 + x**53 + x**52 + x**51 + x**48 + x**47 + x**46 + x**45 + x**42 + x**40 + x**34 + x**32 + x**28 + x**25 + x**24 + x**22 + x**21 + x**20 + x**19 + x**16 + x**13 + x**12 + x**11 + x**5 + x**4 + x**3 + x, x, domain='ZZ')]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 121, in runDecaps
    alg.Decapsulate(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\timer.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 140, in Decapsulate
    mp = self._PKE_decrypt(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\lib\ctru.py", line 93, in _PKE_decrypt
    m0 = ext_mod((self.sk * c) % self.R, self.q2)
  File "C:\Python39\lib\site-packages\sympy\polys\polytools.py", line 70, in wrapper
    g = _sympify(g)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 529, in _sympify
    return sympify(a, strict=True)
  File "C:\Python39\lib\site-packages\sympy\core\sympify.py", line 450, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: [Poly(-2*x**31 + 2*x**30 - 2*x**28 - 2*x**25 + 2*x**24 + 2*x**23 - 4*x**20 - 2*x**19 - 2*x**16 - 2*x**14 + 2*x**13 + 4*x**12 - 2*x**11 + 2*x**9 - 2*x**6 + 2*x**5 + 2*x**4 - 2*x**3 - 2*x**2 - 2*x + 3, x, domain='ZZ'), Poly(x**255 + x**254 + x**253 + x**251 + x**245 + x**244 + x**243 + x**238 + x**236 + x**235 + x**231 + x**229 + x**228 + x**227 + x**225 + x**223 + x**220 + x**219 + x**215 + x**214 + x**208 + x**207 + x**206 + x**203 + x**195 + x**188 + x**185 + x**184 + x**182 + x**181 + x**177 + x**176 + x**170 + x**168 + x**167 + x**165 + x**164 + x**163 + x**162 + x**157 + x**154 + x**153 + x**148 + x**145 + x**143 + x**141 + x**139 + x**138 + x**137 + x**136 + x**135 + x**132 + x**127 + x**126 + x**125 + x**120 + x**116 + x**115 + x**114 + x**111 + x**110 + x**109 + x**108 + x**106 + x**105 + x**103 + x**102 + x**100 + x**98 + x**95 + x**94 + x**93 + x**92 + x**91 + x**88 + x**86 + x**84 + x**81 + x**80 + x**79 + x**77 + x**76 + x**74 + x**70 + x**61 + x**60 + x**59 + x**58 + x**56 + x**55 + x**54 + x**53 + x**52 + x**51 + x**48 + x**47 + x**46 + x**45 + x**42 + x**40 + x**34 + x**32 + x**28 + x**25 + x**24 + x**22 + x**21 + x**20 + x**19 + x**16 + x**13 + x**12 + x**11 + x**5 + x**4 + x**3 + x, x, domain='ZZ')]
18:05:13,265 grpc._server ERROR Exception iterating responses: "Entry" object has no field "inputParametes"
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 125, in runDecaps
    entry.inputParametes = {
  File "pydantic\main.py", line 358, in pydantic.main.BaseModel.__setattr__
ValueError: "Entry" object has no field "inputParametes"
18:07:11,918 grpc._server ERROR Exception iterating responses: a bytes-like object is required, not 'tuple'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 120, in runDecaps
    entry.output = b64encode(alg.Decapsulate(c))
  File "C:\Python39\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'tuple'
18:08:43,97 grpc._server ERROR Exception iterating responses: a bytes-like object is required, not 'tuple'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\ctru_service.py", line 121, in runDecaps
    entry.output = b64encode(alg.Decapsulate(c)).decode('utf-8')
  File "C:\Python39\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'tuple'
18:15:20,556 Error catcher ERROR Unknown except raised __init__() missing 1 required positional argument: 'dv'
18:15:20,558 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:17:24,668 Error catcher ERROR Unknown except raised 'tuple' object has no attribute 'all_coeffs'
18:17:24,668 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:18:33,464 Error catcher ERROR Unknown except raised 'tuple' object has no attribute 'all_coeffs'
18:18:33,464 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:19:32,193 Error catcher ERROR Unknown except raised 'tuple' object has no attribute 'all_coeffs'
18:19:32,202 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:41:41,25 Error catcher ERROR Unknown except raised can only convert an array of size 1 to a Python scalar
18:41:41,25 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:43:22,741 Error catcher ERROR Unknown except raised can only convert an array of size 1 to a Python scalar
18:43:22,743 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:45:29,750 Error catcher ERROR Unknown except raised 'list' object has no attribute 'encode'
18:45:29,751 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:47:13,892 Error catcher ERROR Unknown except raised a bytes-like object is required, not 'DerSequence'
18:47:13,893 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message KYBERKeygenResult is missing required fields: keys,entry
18:48:29,138 grpc._server ERROR Exception iterating responses: parameters
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 114, in runEncaps
    alg = Kyber(request.parameters.n, request.parameters.q, request.parameters.eta, request.parameters.k, request.parameters.du, request.parameters.dv)
AttributeError: parameters
18:52:09,912 grpc._server ERROR Exception iterating responses: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 116, in runEncaps
    alg.pk = (np.array([ Poly(p.decode(), x) for p in DerSequence().decode(b64decode(pkp[0])) ]), b64decode(pkp[1]))
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 116, in <listcomp>
    alg.pk = (np.array([ Poly(p.decode(), x) for p in DerSequence().decode(b64decode(pkp[0])) ]), b64decode(pkp[1]))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
18:55:19,501 grpc._server ERROR Exception iterating responses: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 117, in runEncaps
    alg.pk = (np.array([ Poly(p.decode(), x) for p in DerSequence().decode(b64decode(pkp[0])) ]), b64decode(pkp[1]))
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 117, in <listcomp>
    alg.pk = (np.array([ Poly(p.decode(), x) for p in DerSequence().decode(b64decode(pkp[0])) ]), b64decode(pkp[1]))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
18:56:07,966 grpc._server ERROR Exception iterating responses: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 116, in runEncaps
    print(DerSequence().decode(b64decode(pkp[0]))[0].decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
18:58:07,164 grpc._server ERROR Exception iterating responses: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 116, in runEncaps
    print(DerSequence().decode(b64decode(pkp[0]))[0].decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
19:06:13,336 grpc._server ERROR Exception iterating responses: can only convert an array of size 1 to a Python scalar
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 138, in runEncaps
    entry.output = ";".join([ b64encode(DerSequence(p.item().all_coeffs()).encode()).decode('utf-8') for p in c])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 138, in <listcomp>
    entry.output = ";".join([ b64encode(DerSequence(p.item().all_coeffs()).encode()).decode('utf-8') for p in c])
ValueError: can only convert an array of size 1 to a Python scalar
19:10:43,959 grpc._server ERROR Exception iterating responses: 'numpy.ndarray' object has no attribute 'all_coeffs'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 145, in runEncaps
    entry.output = export_poly_array(c)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in export_poly_array
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in <listcomp>
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
AttributeError: 'numpy.ndarray' object has no attribute 'all_coeffs'
19:12:22,215 grpc._server ERROR Exception iterating responses: 'tuple' object has no attribute 'shape'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 143, in runEncaps
    print(c.shape)
AttributeError: 'tuple' object has no attribute 'shape'
19:15:20,965 grpc._server ERROR Exception iterating responses: iteration over a 0-d array
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 145, in runEncaps
    entry.output = export_poly_array(u)+"!"+export_poly_array(v)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in export_poly_array
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
TypeError: iteration over a 0-d array
19:17:27,448 grpc._server ERROR Exception iterating responses: can only convert an array of size 1 to a Python scalar
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 145, in runEncaps
    entry.output = export_poly_array([u.item(), v.item()])
ValueError: can only convert an array of size 1 to a Python scalar
19:18:30,675 grpc._server ERROR Exception iterating responses: can only convert an array of size 1 to a Python scalar
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 146, in runEncaps
    entry.output = export_poly_array([u.item(), v.item()])
ValueError: can only convert an array of size 1 to a Python scalar
19:19:12,923 grpc._server ERROR Exception iterating responses: can only convert an array of size 1 to a Python scalar
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 147, in runEncaps
    entry.output = export_poly_array([u.item(), v.item()])
ValueError: can only convert an array of size 1 to a Python scalar
19:22:18,800 grpc._server ERROR Exception iterating responses: 'Poly' object is not iterable
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 146, in runEncaps
    entry.output = export_poly_array(u)+";"+export_poly_array(v.item())
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in export_poly_array
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
TypeError: 'Poly' object is not iterable
19:23:01,995 grpc._server ERROR Exception iterating responses: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 158, in runDecaps
    v = import_poly_array(request.data.split(";")[-1])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 51, in import_poly_array
    return np.array([ Poly(DerSequence().decode(b64decode(p)), x) for p in arr ])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 51, in <listcomp>
    return np.array([ Poly(DerSequence().decode(b64decode(p)), x) for p in arr ])
  File "C:\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
19:24:33,773 grpc._server ERROR Exception iterating responses: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 160, in runDecaps
    v = import_poly_array(request.data.split(";")[-1])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 51, in import_poly_array
    return np.array([ Poly(DerSequence().decode(b64decode(p)), x) for p in arr ])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 51, in <listcomp>
    return np.array([ Poly(DerSequence().decode(b64decode(p)), x) for p in arr ])
  File "C:\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
19:27:07,60 grpc._common ERROR Exception serializing message!
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_common.py", line 86, in _transform
    return transformer(message)
google.protobuf.message.EncodeError: Message User is missing required fields: username,emailAddress,userId
19:27:17,561 grpc._server ERROR Exception iterating responses: 'numpy.ndarray' object has no attribute 'all_coeffs'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 149, in runEncaps
    entry.output = export_poly_array(u)
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in export_poly_array
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 66, in <listcomp>
    return ";".join([b64encode(DerSequence(p.all_coeffs()).encode()).decode('utf-8') for p in arr])
AttributeError: 'numpy.ndarray' object has no attribute 'all_coeffs'
19:29:57,621 grpc._server ERROR Exception iterating responses: output
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\grpc\_server.py", line 461, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "D:\personal\master\MSI1\aset\proiect\MS1--KEM-over-NTRU\source\backend\controllers\kyber_service.py", line 166, in runDecaps
    "c": request.output
AttributeError: output
